################### DataSource Configuration ##########################
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Cateye@2018
  table:
    china_city_polygon: s_ods_city_simplify
    t_log: t_log
    t_sys_user: t_sys_user
    t_sys_role: t_sys_role