################### DataSource Configuration ##########################
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rm-2ze378rwv37etj956bo.pg.rds.aliyuncs.com:3432/postgres
    username: postgres
    password: Cateye@2018
  table:
    china_city_polygon: s_ods_city_simplify
    t_log: t_log