server:
  port: 9999
spring:
  application:
    name: lbi-web
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rm-2ze378rwv37etj956bo.pg.rds.aliyuncs.com:3432/postgres
    username: postgres
    password: Cateye@2018
  mvc:
    favicon:
      enabled: true
log:
  home: logs